"""M13-A storage boundary: the replaceable persistence surface for reader + M10 state.

The local app uses `LocalFileStore` (`ReaderStore`). The browser-side IndexedDB `BrowserStore`
is an asynchronous structured-data foundation, not yet a drop-in implementation of these
synchronous Python protocols: audio, filesystem paths, and session locks remain local-only.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Any, Protocol


class LongitudinalStore(Protocol):
    """Public M10 persistence surface (`ProgressStore` today)."""

    def save_practice(self, record: dict[str, Any]) -> None: ...

    def practice_records(self) -> list[dict[str, Any]]: ...

    def load_cache(self) -> dict[str, Any]: ...

    def save_cache(self, cache: dict[str, Any], sessions: set[str] | None = None) -> None: ...

    def ledger(self) -> list[dict[str, Any]]: ...

    def append_ledger(self, lines: list[dict[str, Any]]) -> None: ...

    def transitions_log(self) -> list[dict[str, Any]]: ...

    def append_transitions(self, lines: list[dict[str, Any]]) -> None: ...


class UserStore(Protocol):
    """Reader + M9 snapshots + M10 store access used by M9/M10/M12 and ReaderService."""

    def session_ids(self) -> list[str]: ...

    def create_session(self, session: dict[str, Any]) -> None: ...

    def save_session(self, session: dict[str, Any]) -> None: ...

    def load_session(self, sid: str) -> dict[str, Any]: ...

    def save_article(self, article: dict[str, Any]) -> None: ...

    def load_article(self, article_id: str) -> dict[str, Any]: ...

    def attempt_exists(self, sid: str, aid: str) -> bool: ...

    def save_attempt(self, attempt: dict[str, Any]) -> None: ...

    def load_attempt(self, sid: str, aid: str) -> dict[str, Any]: ...

    def save_job(self, job: dict[str, Any]) -> None: ...

    def load_job(self, sid: str, aid: str, jid: str) -> dict[str, Any]: ...

    def save_view(self, job: dict[str, Any], view: dict[str, Any]) -> None: ...

    def load_view(self, job: dict[str, Any]) -> dict[str, Any] | None: ...

    def save_summary(self, sid: str, summary: dict[str, Any]) -> None: ...

    def load_summary(self, sid: str) -> dict[str, Any] | None: ...

    def save_coaching(self, sid: str, coaching: dict[str, Any]) -> None: ...

    def load_coaching(self, sid: str) -> dict[str, Any] | None: ...

    def save_reading_feedback(self, sid: str, feedback: dict[str, Any]) -> None: ...

    def load_reading_feedback(self, sid: str) -> dict[str, Any] | None: ...

    def append_event(self, sid: str, kind: str, **data: Any) -> None: ...

    def events(self, sid: str) -> list[dict[str, Any]]: ...

    def session_lock(self, sid: str) -> AbstractContextManager[None] | Iterator[None]: ...

    def write_audio(self, sid: str, aid: str, name: str, data: bytes) -> Path: ...

    def write_result(self, job: dict[str, Any], result_json: str) -> None: ...

    def write_job_file(self, job: dict[str, Any], name: str, data: bytes) -> Path: ...

    def load_boundary(self, job: dict[str, Any]) -> dict[str, Any] | None: ...

    def attempt_fingerprint(self, sid: str, aid: str, session: dict[str, Any],
                            article: dict[str, Any] | None) -> str | None: ...

    def progress_store(self) -> LongitudinalStore: ...
